//
// Copyright (c) 2006 by Conor O'Mahony.
// For enquiries, please email GubuSoft@GubuSoft.com.
// Please keep all copyright notices below.
// Original author of TreeView script is Marcelino Martins.
//
// This document includes the TreeView script.
// The TreeView script can be found at http://www.TreeView.net.
// The script is Copyright (c) 2006 by Conor O'Mahony.
//
// You can find general instructions for this file at www.treeview.net.
//

USETEXTLINKS = 1
STARTALLOPEN = 0
USEFRAMES = 0
USEICONS = 1
WRAPTEXT = 1
PRESERVESTATE = 1
HIGHLIGHT = 1
HIGHLIGHT_COLOR = 'green'
HIGHLIGHT_BG = 'white'
PRESERVESTATE=1

//
// The following code constructs the tree.  This code produces a tree that looks like:
// 
// Tree Options
//  - Expand for example with pics and flags
//    - United States
//      - Boston
//      - Tiny pic of New York City
//      - Washington
//    - Europe
//      - London
//      - Lisbon
//  - Types of node
//    - Expandable with link
//      - London
//    - Expandable without link
//      - NYC
//    - Opens in new window
//

var direccion = "/Delphos";
//var direccion = "file:///D:/Documents/delphos/Delphos/web";

foldersTree = gFld("<b>DELPHOS</b>", direccion+"/FamiliasEnAccion/index.jsp")
  foldersTree.treeID = "Frameless"

aux1 = insFld(foldersTree, gFld("<b>FAMILIAS EN ACCI&Oacute;N</b>", "javascript:undefined"))
    aux2 = insFld(aux1, gFld("ATENCI&Oacute;N AL USUARIO", "javascript:undefined"))
        aux3 = insFld(aux2, gFld("Encuentros y Reuniones", "javascript:undefined"))
            aux4 = insFld(aux3, gFld("Reuniones", direccion+"/ComunFS/EncuentrosOReuniones.jsp"))
            aux4 = insFld(aux3, gFld("Asistencia", direccion+"/ComunFS/AsistenciaReuniones.jsp"))
            aux4 = insFld(aux3, gFld("Actividades", direccion+"/ComunFS/ActividadesRealizadas.jsp"))
            aux4 = insFld(aux3, gFld("Asistentes", direccion+"/ComunFS/AsistentesReuniones.jsp"))
        aux3 = insFld(aux2, gFld("Reclamos", "javascript:undefined"))
            aux4 = insFld(aux3, gFld("Registro", direccion+"/FamiliasEnAccion/RegistroReclamos.jsp"))
            aux4 = insFld(aux3, gFld("Documentos", direccion+"/FamiliasEnAccion/DocumentosReclamos.jsp"))
            aux4 = insFld(aux3, gFld("Afectados", direccion+"/FamiliasEnAccion/AfectadosReclamo.jsp"))
            aux4 = insFld(aux3, gFld("Respuestas", direccion+"/FamiliasEnAccion/RespuestaReclamo.jsp"))
        aux3 = insFld(aux2, gFld("Quejas", "javascript:undefined"))
            aux4 = insFld(aux3, gFld("Registro", direccion+"/FamiliasEnAccion/RegistroQuejas.jsp"))
            aux4 = insFld(aux3, gFld("Documentos", direccion+"/FamiliasEnAccion/DocumentoQuejas.jsp"))
            aux4 = insFld(aux3, gFld("Afectados", direccion+"/FamiliasEnAccion/AfectadosQuejas.jsp"))
            aux4 = insFld(aux3, gFld("Respuestas", direccion+"/FamiliasEnAccion/RespuestaQuejas.jsp"))
        aux3 = insFld(aux2, gFld("Configuraci&oacute;n B&aacute;sica", "javascript:undefined"))
            aux4 = insFld(aux3, gFld("Tipo Actividad", direccion+"/TablasBasicas/TipoActividad.jsp"))
            aux4 = insFld(aux3, gFld("Clasificaci&oacute;n Reclamo", direccion+"/TablasBasicas/ReclamoClasificacion.jsp"))
            aux4 = insFld(aux3, gFld("Tipo Reclamo", direccion+"/TablasBasicas/ReclamoTipo.jsp"))
            aux4 = insFld(aux3, gFld("Clasifica Respuesta", direccion+"/TablasBasicas/RespuestaClasificacion.jsp"))
            aux4 = insFld(aux3, gFld("Tipo Satisfacci&oacute;n", direccion+"/TablasBasicas/SatisfaccionTipo.jsp"))
            aux4 = insFld(aux3, gFld("Clasificaci&oacute;n Queja", direccion+"/TablasBasicas/QuejaClasificacion.jsp"))
            aux4 = insFld(aux3, gFld("Tipo Queja", direccion+"/TablasBasicas/TipoQueja.jsp"))

      aux2 = insFld(aux1, gFld("VINCULACI&Oacute;N", "javascript:undefined"))
        aux3 = insFld(aux2, gFld("Inscripci&oacute;n", "javascript:undefined"))
            aux4 = insFld(aux3, gFld("Registro", direccion+"/FamiliasEnAccion/Vinculacion1.jsp"))
            aux4 = insFld(aux3, gFld("Documentos", direccion+"/FamiliasEnAccion/DocumentosInscripcion.jsp"))
            aux4 = insFld(aux3, gFld("Grupos Titulares", direccion+"/FamiliasEnAccion/GrupoTitular.jsp"))
            aux4 = insFld(aux3, gFld("Titular Familia", direccion+"/FamiliasEnAccion/TitularFamilia.jsp"))
            aux4 = insFld(aux3, gFld("Beneficiarios", direccion+"/FamiliasEnAccion/Beneficiario.jsp"))
        aux3 = insFld(aux2, gFld("Novedad", "javascript:undefined"))
            aux4 = insFld(aux3, gFld("Registro", direccion+"/FamiliasEnAccion/RegistroNovedad.jsp"))
            aux4 = insFld(aux3, gFld("Novedad por Campo", direccion+"/FamiliasEnAccion/NovedadPorCampo.jsp"))
            aux4 = insFld(aux3, gFld("Documentos", direccion+"/FamiliasEnAccion/DocumentosNovedad.jsp"))
        aux3 = insFld(aux2, gFld("Poblaci&oacute;n", "javascript:undefined"))
            aux4 = insFld(aux3, gFld("Poblaci&oacute;n", direccion+"/ComunFS/Poblacion.jsp"))
            aux4 = insFld(aux3, gFld("Consultas", "javascript:undefined"))
        aux3 = insFld(aux2, gFld("Configuraci&oacute;n B&aacute;sica", "javascript:undefined"))
            aux4 = insFld(aux3, gFld("Tipo Poblaci&oacute;n", direccion+"/TablasBasicas/TipoPoblacion.jsp"))
            aux4 = insFld(aux3, gFld("Estado Familia", direccion+"/TablasBasicas/EstadoFamilia.jsp"))
            aux4 = insFld(aux3, gFld("Tipo Titular", direccion+"/TablasBasicas/TipoTitular.jsp"))
            aux4 = insFld(aux3, gFld("Estado Titular", direccion+"/TablasBasicas/EstadoTitular.jsp"))
            aux4 = insFld(aux3, gFld("Clase Grupo Titular", direccion+"/TablasBasicas/ClaseGrupoTitular.jsp"))
            aux4 = insFld(aux3, gFld("Causal Novedad", direccion+"/TablasBasicas/NovedadCausal.jsp"))
            aux4 = insFld(aux3, gFld("Causal Documentos", direccion+"/TablasBasicas/DocumentoCausal.jsp"))

      aux2 = insFld(aux1, gFld("EDUCACI&Oacute;N", "javascript:undefined"))
        aux3 = insFld(aux2, gFld("Escolaridad", direccion+"/FamiliasEnAccion/Escolaridad.jsp"))
        aux3 = insFld(aux2, gFld("Novedad Escolaridad", direccion+"/FamiliasEnAccion/NovedadEscolaridad.jsp"))
        aux3 = insFld(aux2, gFld("Registro Periodico", direccion+"/FamiliasEnAccion/RegistroPeriodicoEscolaridad.jsp"))
        aux3 = insFld(aux2, gFld("Cumple Escolaridad", direccion+"/FamiliasEnAccion/CumplimientoEscolaridad.jsp"))
        aux3 = insFld(aux2, gFld("Configuraci&oacute;n B&aacute;sica", "javascript:undefined"))
            aux4 = insFld(aux3, gFld("Estado Escolaridad", direccion+"/TablasBasicas/EscolaridadEstado.jsp"))
            aux4 = insFld(aux3, gFld("Firmas Autorizadas", direccion+"/TablasBasicas/FirmasAutorizadas.jsp"))

      aux2 = insFld(aux1, gFld("SALUD", "javascript:undefined"))
        aux3 = insFld(aux2, gFld("Inscripcion IPS", direccion+"/FamiliasEnAccion/InscripcionIPS.jsp"))
        aux3 = insFld(aux2, gFld("Novedad Entidad Salud", "javascript:undefined"))
        aux3 = insFld(aux2, gFld("Atenciones en Salud", direccion+"/FamiliasEnAccion/AtencionesEnSalud.jsp"))
        aux3 = insFld(aux2, gFld("Registro Controles", direccion+"/FamiliasEnAccion/RegistroControles.jsp"))
        aux3 = insFld(aux2, gFld("Cumplimiento Salud", direccion+"/FamiliasEnAccion/SaludCumplimiento.jsp"))
        aux3 = insFld(aux2, gFld("Configuraci&oacute;n B&aacute;sica", "javascript:undefined"))
            aux4 = insFld(aux3, gFld("Actividad Salud", direccion+"/TablasBasicas/ActividadSalud.jsp"))
            aux4 = insFld(aux3, gFld("Diagn&oacute;sticos", direccion+"/TablasBasicas/Diagnostico.jsp"))
            aux4 = insFld(aux3, gFld("Estado Inscripto IPS", direccion+"/TablasBasicas/EstadoIncripIps.jsp"))
            aux4 = insFld(aux3, gFld("Finalidad Consulta", direccion+"/TablasBasicas/FinalidadConsulta.jsp"))
            aux4 = insFld(aux3, gFld("Firma Autorizada", direccion+"/TablasBasicas/FirmasAutorizadas.jsp"))
            aux4 = insFld(aux3, gFld("RIPS Periodicos", "javascript:undefined")) //direccion+"/TablasBasicas/RipsPeriodicoIps.jsp"))

      aux2 = insFld(aux1, gFld("NUTRICI&Oacute;N", "javascript:undefined"))
        aux3 = insFld(aux2, gFld("Valoraci&oacute;n Nutricional", direccion+"/FamiliasEnAccion/ValoracionNutricional.jsp"))
        aux3 = insFld(aux2, gFld("Actividad Nutricional", direccion+"/FamiliasEnAccion/ActividadesNutricionales.jsp"))

      aux2 = insFld(aux1, gFld("VIOLENCIA INTRAFAMILIAR", "javascript:undefined"))
        aux3 = insFld(aux2, gFld("Registro Violencia", direccion+"/FamiliasEnAccion/RegistroAccionViolencia.jsp"))
        aux3 = insFld(aux2, gFld("Configuraci&oacute;n B&aacute;sica", "javascript:undefined"))
            aux4 = insFld(aux3, gFld("Tipo Violencia", direccion+"/TablasBasicas/TipoViolencia.jsp"))

      aux2 = insFld(aux1, gFld("ESTIMULACI&Oacute;N TEMPRANA", "javascript:undefined"))
        aux3 = insFld(aux2, gFld("Registro", direccion+"/FamiliasEnAccion/RegistroEstimulacionTemprana.jsp"))
        aux3 = insFld(aux2, gFld("Configuraci&oacute;n B&aacute;sica", "javascript:undefined"))
            aux3 = insFld(aux3, gFld("Tipo Estimulaci&oacute;n", direccion+"/TablasBasicas/TipoEstimulacion.jsp"))

      aux2 = insFld(aux1, gFld("SUBSIDIOS", "javascript:undefined"))
        aux3 = insFld(aux2, gFld("Subsidios", direccion+"/FamiliasEnAccion/Subsidios.jsp"))
        aux3 = insFld(aux2, gFld("Subsidios Municipio", direccion+"/FamiliasEnAccion/SubsidiosMunicipio.jsp"))
        aux3 = insFld(aux2, gFld("Subsidio Potencial", direccion+"/FamiliasEnAccion/SubsidioPotencial.jsp"))
        aux3 = insFld(aux2, gFld("Subsidio Asignado", direccion+"/FamiliasEnAccion/SubsidioAsignado.jsp"))
        aux3 = insFld(aux2, gFld("Configuraci&oacute;n B&aacute;sica", "javascript:undefined"))
            aux4 = insFld(aux3, gFld("Categor&iacute;a Subsidio", direccion+"/TablasBasicas/SubsidioCategoria.jsp"))
            aux4 = insFld(aux3, gFld("Tipo Subsidio", direccion+"/TablasBasicas/TipoSubsidio.jsp"))
            aux4 = insFld(aux3, gFld("Tipo Educaci&oacute;n", direccion+"/TablasBasicas/TipoEducacion.jsp"))
            aux4 = insFld(aux3, gFld("Grado Escolaridad", direccion+"/TablasBasicas/EscolaridadGrado.jsp"))
            aux4 = insFld(aux3, gFld("Grupo Grado Escolar", direccion+"/TablasBasicas/EscGrupoGrado.jsp"))

      aux2 = insFld(aux1, gFld("BI (Gesti&oacute;n Informaci&oacute;n)", "javascript:undefined"))

      aux2 = insFld(aux1, gFld("SEGURIDAD", "javascript:undefined"))
            aux3 = insFld(aux2, gFld("Usuarios Sistema", direccion+"/TablasBasicas/UsuariosSistema.jsp"))
            aux3 = insFld(aux2, gFld("Estados Grupos de Seguridad", direccion+"/TablasBasicas/EstadoGrupoSeguridad.jsp"))
            aux3 = insFld(aux2, gFld("Grupos de Seguridad", direccion+"/TablasBasicas/GrupoSeguridad.jsp"))
            aux3 = insFld(aux2, gFld("Lista Opciones", direccion+"/TablasBasicas/ListaOpcion.jsp"))
            aux3 = insFld(aux2, gFld("Nivel Seguridad Opcion", direccion+"/TablasBasicas/NivelSeguridadOpcion.jsp"))
            aux3 = insFld(aux2, gFld("Opcion Grupo Seguridad", direccion+"/TablasBasicas/OpcionGrupoSeguridad.jsp"))
            aux3 = insFld(aux2, gFld("Opciones Usuario", direccion+"/TablasBasicas/OpcionUsuario.jsp"))
            aux3 = insFld(aux2, gFld("Estado Usuario Sistema", direccion+"/TablasBasicas/EstadoUsuarioSistema.jsp"))
            aux3 = insFld(aux2, gFld("Copias Seguridad", "javascript:undefined"))
            aux3 = insFld(aux2, gFld("Restaurar Copia", "javascript:undefined"))

      aux2 = insFld(aux1, gFld("CONFIGURACI&Oacute;N GENERAL", "javascript:undefined"))
        aux3 = insFld(aux2, gFld("Marco General", "javascript:undefined"))
            aux4 = insFld(aux3, gFld("Empresa Sistema", "javascript:undefined"))
            aux4 = insFld(aux3, gFld("Cupos Asignados", "javascript:undefined"))
            aux4 = insFld(aux3, gFld("Requisitos Familias", "javascript:undefined"))
            aux4 = insFld(aux3, gFld("Estrategias", "javascript:undefined"))
            aux4 = insFld(aux3, gFld("Plan Acci&oacute;n", "javascript:undefined"))

        aux3 = insFld(aux2, gFld("Configuraci&oacute;n B&aacute;sica", "javascript:undefined"))
            aux4 = insFld(aux3, gFld("&Aacute;rea Geogr&aacute;fica", "javascript:undefined"))
            aux4 = insFld(aux3, gFld("B&aacute;sicas", "javascript:undefined"))
            aux4 = insFld(aux3, gFld("Entidades", "javascript:undefined"))
            aux4 = insFld(aux3, gFld("Planes", "javascript:undefined"))

aux1 = insFld(foldersTree, gFld("<b>SISTEMA DE SALUD</b>", "javascript:undefined"))
    aux2 = insFld(aux1, gFld("CONTRATACI&Oacute;N", "javascript:undefined"))
        aux3 = insFld(aux2, gFld("Minutas", "javascript:undefined"))
            aux4 = insFld(aux3, gFld("Contratos", direccion+"/Salud/Contrato.jsp"))
            aux4 = insFld(aux3, gFld("Actividades", direccion+"/Salud/Actividades.jsp"))
            aux4 = insFld(aux3, gFld("Modificaciones", direccion+"/Salud/Modificaciones.jsp"))
            aux4 = insFld(aux3, gFld("Obligaciones", direccion+"/Salud/Obligaciones.jsp"))
            aux4 = insFld(aux3, gFld("Observaciones", direccion+"/Salud/Observaciones.jsp"))
            aux4 = insFld(aux3, gFld("Poblaci&oacute;n Contrato", direccion+"/Salud/PoblacionContrato.jsp"))
            aux4 = insFld(aux3, gFld("Requisitos", direccion+"/Salud/Requisitos.jsp"))
            aux4 = insFld(aux3, gFld("Rubro Presupuestal", direccion+"/Salud/RubroPptoContrato.jsp"))
            aux4 = insFld(aux3, gFld("Funciones", direccion+"/Salud/Funcion.jsp"))
            aux4 = insFld(aux3, gFld("Funci&oacute;n Tipo Persona", direccion+"/Salud/FuncionTipoPersona.jsp"))
            aux4 = insFld(aux3, gFld("Pago Compartido", direccion+"/Salud/PagoCompartido.jsp"))
        aux3 = insFld(aux2, gFld("Documentos o Soportes", "javascript:undefined"))
            aux4 = insFld(aux3, gFld("Documento Asociado", direccion+"/Salud/DocumentoAsociado.jsp"))
            aux4 = insFld(aux3, gFld("Campo IPS-EAPB", direccion+"/Salud/CampoIPSEAPB.jsp"))
            aux4 = insFld(aux3, gFld("Formato Relacionado", direccion+"/Salud/FormatoRelacionado.jsp"))
            aux4 = insFld(aux3, gFld("P&oacute;lizas ", direccion+"/Salud/Polizas.jsp"))
            aux4 = insFld(aux3, gFld("Soporte Modalidad", direccion+"/Salud/SoporteModalidad.jsp"))
            aux4 = insFld(aux3, gFld("Soportes Contrato", direccion+"/Salud/SoporteContrato.jsp"))
        aux3 = insFld(aux2, gFld("Actas y Liquidaciones", "javascript:undefined"))
            aux4 = insFld(aux3, gFld("Actas por Contrato", direccion+"/Salud/ActasPorContrato.jsp"))
            aux4 = insFld(aux3, gFld("Funcionarios Actas", direccion+"/Salud/FuncionariosActas.jsp"))
            aux4 = insFld(aux3, gFld("Interventor&iacute;a", direccion+"/Salud/Interventoria.jsp"))
            aux4 = insFld(aux3, gFld("Liquidaci&oacute;n", direccion+"/Salud/Liquidacion.jsp"))
            aux4 = insFld(aux3, gFld("Plan Interventor&iacute;a", direccion+"/Salud/PlanInterventoria.jsp"))
        aux3 = insFld(aux2, gFld("Novedades", "javascript:undefined"))
            aux4 = insFld(aux3, gFld("Pagos Contrato", direccion+"/Salud/PagosContrato.jsp"))
            aux4 = insFld(aux3, gFld("Tr&aacute;mite de Glosas", direccion+"/Salud/TramiteGlosas.jsp"))
            aux4 = insFld(aux3, gFld("Usuarios Pagados", direccion+"/Salud/UsuariosPagados.jsp"))       
        aux3 = insFld(aux2, gFld("Configuraci&oacute;n B&aacute;sica", "javascript:undefined"))
            aux4 = insFld(aux3, gFld("Parametrizaci&oacute;n", "javascript:undefined"))
                aux5 = insFld(aux4, gFld("Tipo Contrato", direccion+"/TablasBasicas/TipoContrato.jsp"))
                aux5 = insFld(aux4, gFld("Aplicaci&oacute;n Contrato", direccion+"/TablasBasicas/AplicacionContrato.jsp"))
                aux5 = insFld(aux4, gFld("Clase Contrato", direccion+"/TablasBasicas/ClaseContrato.jsp"))
                aux5 = insFld(aux4, gFld("Modalidad Contrato", direccion+"/TablasBasicas/ModalidadContrato.jsp"))
                aux5 = insFld(aux4, gFld("Estado Contrato", direccion+"/TablasBasicas/EstadoContrato.jsp"))
                aux5 = insFld(aux4, gFld("Fases Contrato", direccion+"/TablasBasicas/TipoFaseContrato.jsp"))
                aux5 = insFld(aux4, gFld("Tipo Intervenci&oacute;n", direccion+"/TablasBasicas/TipoIntervencContrato.jsp"))
                aux5 = insFld(aux4, gFld("Soporte Modalidad", direccion+"/TablasBasicas/SoporteModalCto.jsp"))
                aux5 = insFld(aux4, gFld("Formatos IPS-EAPB", direccion+"/TablasBasicas/FormatoIpsEapb.jsp"))
            aux4 = insFld(aux3, gFld("B&aacute;sicas", "javascript:undefined"))
                aux5 = insFld(aux4, gFld("Tipos Requisitos", direccion+"/TablasBasicas/TipoRequisito.jsp"))
                aux5 = insFld(aux4, gFld("Tipos Soportes", direccion+"/TablasBasicas/TipoSoporte.jsp"))            
                aux5 = insFld(aux4, gFld("Tipos Actas", direccion+"/TablasBasicas/TipoActaContrato.jsp"))            
                aux5 = insFld(aux4, gFld("Tipos P&oacute;lizas", direccion+"/TablasBasicas/TipoPoliza.jsp"))
                aux5 = insFld(aux4, gFld("Tipo Obligaci&oacute;n", direccion+"/TablasBasicas/TipoObligContrato.jsp"))            
                aux5 = insFld(aux4, gFld("Espec&iacute;fico Glosas", direccion+"/TablasBasicas/ConcepEspecifGlosa.jsp"))
                aux5 = insFld(aux4, gFld("Generalidad Glosas", direccion+"/TablasBasicas/ConcepGeneralGlosa.jsp"))
                aux5 = insFld(aux4, gFld("Estado Cumple", direccion+"/TablasBasicas/EstadoCumplimiento.jsp"))
                aux5 = insFld(aux4, gFld("Estado Registro", direccion+"/TablasBasicas/EstadoRegistro.jsp"))
                aux5 = insFld(aux4, gFld("Manual Glosas", direccion+"/TablasBasicas/ManualConcGlosa.jsp"))
                aux5 = insFld(aux4, gFld("Rubro Presupuestal", direccion+"/TablasBasicas/RubroPresupuestal.jsp"))

      aux2 = insFld(aux1, gFld("POBLACI&Oacute;N-<font size = '1.8px'>ASEGURAMIENTO</font>", "javascript:undefined"))
        
        aux3 = insFld(aux2, gFld("Autorizaci&oacute;n", direccion+"/Salud/Autorizacion.jsp"))

        aux3 = insFld(aux2, gFld("Poblaci&oacute;n", direccion+"/ComunFS/Poblacion.jsp"))

        aux3 = insFld(aux2, gFld("Poblaci&oacute;n Peri&oacute;dica", "javascript:undefined"))

        aux3 = insFld(aux2, gFld("Recepci&oacute;n Archivo", direccion+"/Salud/CargarArchivo.jsp"))

        aux3 = insFld(aux2, gFld("Entrega Bases de Datos", direccion+"/Salud/EntregaBD.jsp"))

        aux3 = insFld(aux2, gFld("Detalle Archivo", "javascript:undefined"))
            aux4 = insFld(aux3, gFld("Estructura Archivo", direccion+"/Salud/EstructuraArchivo.jsp"))
            aux4 = insFld(aux3, gFld("Detalle Inconsistencia", direccion+"/Salud/DetalleIncosistencia.jsp"))
            aux4 = insFld(aux3, gFld("Novedad Dato", direccion+"/Salud/NovedadDato.jsp"))

        aux3 = insFld(aux2, gFld("Generaci&oacute;n Archivos", "javascript:undefined"))
            aux4 = insFld(aux3, gFld("Maestro Poblaci&oacute;n", "javascript:undefined"))
            aux4 = insFld(aux3, gFld("Novedad Poblaci&oacute;n", "javascript:undefined"))
            aux4 = insFld(aux3, gFld("Traslados", "javascript:undefined"))
            aux4 = insFld(aux3, gFld("Aportantes", "javascript:undefined"))

        aux3 = insFld(aux2, gFld("Glosas Afiliaci&oacute;n", "javascript:undefined"))
            aux4 = insFld(aux3, gFld("Glosas Recibidas", direccion+"/Salud/GlosasRecibidas.jsp"))
            aux4 = insFld(aux3, gFld("Respuesta Glosas", direccion+"/Salud/RespuestaGlosas.jsp"))

        aux3 = insFld(aux2, gFld("BI - Gesti&oacute;n Informaci&oacute;n", "javascript:undefined"))
            aux4 = insFld(aux3, gFld("An&aacute;lisis Multiafiliaci&oacute;n", "javascript:undefined"))
            aux4 = insFld(aux3, gFld("Recursos Afiliaci&oacute;n", "javascript:undefined"))        
            aux4 = insFld(aux3, gFld("Inteligencia Negocios", "javascript:undefined"))
        
        aux3 = insFld(aux2, gFld("Configuraci&oacute;n B&aacute;sica", "javascript:undefined"))
            aux4 = insFld(aux3, gFld("Datos B&aacute;sicos", "javascript:undefined"))
                aux5 = insFld(aux4, gFld("Criterio Tipo Identificaci&oacute;n", direccion+"/TablasBasicas/CriterioTipoIdent.jsp"))
                aux5 = insFld(aux4, gFld("Estado Civil", direccion+"/TablasBasicas/EstadoCivil.jsp"))
                aux5 = insFld(aux4, gFld("Grupo Poblacional", direccion+"/TablasBasicas/GrupoPoblacion.jsp"))
                aux5 = insFld(aux4, gFld("Grupos de Edad", direccion+"/TablasBasicas/GrupoEdad.jsp"))
                aux5 = insFld(aux4, gFld("Nombres por Sexo", direccion+"/TablasBasicas/NombresXSexo.jsp"))
                aux5 = insFld(aux4, gFld("Parentesco", direccion+"/TablasBasicas/TipoParentesco.jsp"))
                aux5 = insFld(aux4, gFld("Pertenencia &Eacute;tnica", direccion+"/TablasBasicas/Etnia.jsp"))
                aux5 = insFld(aux4, gFld("Sexo", direccion+"/TablasBasicas/Sexo.jsp"))
                aux5 = insFld(aux4, gFld("Tipo Identificaci&oacute;n", direccion+"/TablasBasicas/TipoIdentificacion.jsp"))
                aux5 = insFld(aux4, gFld("Tipo Poblaci&oacute;n", direccion+"/TablasBasicas/TipoPoblacion.jsp"))
                aux5 = insFld(aux4, gFld("Tipo Grupo Edad", direccion+"/TablasBasicas/TipoGrupoEdad.jsp"))
                aux5 = insFld(aux4, gFld("Medida Edad", direccion+"/TablasBasicas/UnidadMedidaEdad.jsp"))
            aux4 = insFld(aux3, gFld("Afiliaci&oacute;n", "javascript:undefined"))
                aux5 = insFld(aux4, gFld("Afiliado Estructura C&oacute;digo Novedad", direccion+"/TablasBasicas/EstructNovedades.jsp"))
                aux5 = insFld(aux4, gFld("Aplica Novedad R&eacute;gimen", direccion+"/TablasBasicas/AplicacNovedadRegimen.jsp"))
                aux5 = insFld(aux4, gFld("Capacidad Pago", direccion+"/TablasBasicas/CapacidadPagoUsua.jsp"))
                aux5 = insFld(aux4, gFld("Causal Traslado", direccion+"/TablasBasicas/CausalTraslado.jsp"))
                aux5 = insFld(aux4, gFld("Condici&oacute;n Beneficiario", direccion+"/TablasBasicas/CondicionBeneficiario.jsp"))
                aux5 = insFld(aux4, gFld("Condici&oacute;n Usuario", direccion+"/TablasBasicas/CondicionUsuario.jsp"))
                aux5 = insFld(aux4, gFld("Estado Usuario", direccion+"/TablasBasicas/EstadoUsuaPoblac.jsp"))
                aux5 = insFld(aux4, gFld("Estado Afiliaci&oacute;n", direccion+"/TablasBasicas/EstadoAfiliacion.jsp"))
                aux5 = insFld(aux4, gFld("Estrato o Nivel", direccion+"/TablasBasicas/EstratoSocioEconomico.jsp"))
                aux5 = insFld(aux4, gFld("Modalidad Subsidio", direccion+"/TablasBasicas/ModalidadSubsidio.jsp"))
                aux5 = insFld(aux4, gFld("Novedad Dato Afiliaci&oacute;n", direccion+"/TablasBasicas/NovedadCampo.jsp"))
                aux5 = insFld(aux4, gFld("R&eacute;gimen", direccion+"/TablasBasicas/Regimen.jsp"))
                aux5 = insFld(aux4, gFld("Tipo Afiliado", direccion+"/TablasBasicas/TipoAfiliado.jsp"))
                aux5 = insFld(aux4, gFld("Tipo Aportante", direccion+"/TablasBasicas/TipoAportante.jsp"))
                aux5 = insFld(aux4, gFld("Tipo Causal Traslado", direccion+"/TablasBasicas/TipoCausaTraslado.jsp"))
                aux5 = insFld(aux4, gFld("Tipo Cotizante", direccion+"/TablasBasicas/TipoCotizante.jsp"))
                aux5 = insFld(aux4, gFld("Tipo P&oacute;liza", direccion+"/TablasBasicas/TipoPoliza.jsp"))
                aux5 = insFld(aux4, gFld("Tipo Novedad", direccion+"/TablasBasicas/TipoNovedad.jsp"))            
            aux4 = insFld(aux3, gFld("Archivos", "javascript:undefined"))
                aux5 = insFld(aux4, gFld("Clase Operaci&oacute;n", direccion+"/TablasBasicas/ClaseOperArch.jsp"))
                aux5 = insFld(aux4, gFld("Sigla Archivo BDUA", direccion+"/TablasBasicas/SiglaArchBdua.jsp"))
                aux5 = insFld(aux4, gFld("Tipo Inconsistencia", direccion+"/TablasBasicas/TipoIncArchivo.jsp"))
                aux5 = insFld(aux4, gFld("Tipo Archivo Afiliaci&oacute;n", direccion+"/TablasBasicas/TipoArchivo.jsp"))
                aux5 = insFld(aux4, gFld("Tipo Estructura", direccion+"/TablasBasicas/TipoEstructArch.jsp"))
            aux4 = insFld(aux3, gFld("Glosas", "javascript:undefined"))
                aux5 = insFld(aux4, gFld("Clase Glosa", direccion+"/TablasBasicas/ClaseGlosaAfil.jsp"))
                aux5 = insFld(aux4, gFld("&Iacute;ndice Glosa", direccion+"/TablasBasicas/IndiceGlosaArchAfil.jsp"))
                aux5 = insFld(aux4, gFld("Tipo Glosa", direccion+"/TablasBasicas/TipoGlosaArchAfil.jsp"))
                aux5 = insFld(aux4, gFld("Tipo Glosa Traslado", direccion+"/TablasBasicas/TipoGlosaTrasl.jsp"))

      aux2 = insFld(aux1, gFld("COMPROBADOR DERECHOS", "javascript:undefined"))        
        aux3 = insFld(aux2, gFld("Comprobar Derechos", direccion+"/Salud/ComprobadorDerechos.jsp"))
        aux3 = insFld(aux2, gFld("Hist&oacute;rico Consultas", direccion+"/Salud/HistoricoConsultas.jsp"))
        aux3 = insFld(aux2, gFld("Consultas BDUA", "javascript:undefined"))
        aux3 = insFld(aux2, gFld("Consultas SIRI", "javascript:undefined"))

      aux2 = insFld(aux1, gFld("ATENCI&Oacute;N AL USUARIO", "javascript:undefined"))
        aux3 = insFld(aux2, gFld("Encuentros y Reuniones", "javascript:undefined"))
            aux4 = insFld(aux3, gFld("Reuniones", direccion+"/ComunFS/EncuentrosOReuniones.jsp"))
            aux4 = insFld(aux3, gFld("Asistencia", direccion+"/ComunFS/AsistenciaReuniones.jsp"))
            aux4 = insFld(aux3, gFld("Actividades", direccion+"/ComunFS/ActividadesRealizadas.jsp"))
            aux4 = insFld(aux3, gFld("Asistentes Externos", direccion+"/ComunFS/AsistentesReuniones.jsp"))
            
        aux3 = insFld(aux2, gFld("Reclamos", "javascript:undefined"))
            aux4 = insFld(aux3, gFld("Registro Reclamo", direccion+"/Salud/SaludReclamo.jsp"))
            aux4 = insFld(aux3, gFld("Documentos Reclamo", direccion+"/FamiliasEnAccion/DocumentosReclamos.jsp"))
            aux4 = insFld(aux3, gFld("Afectados Reclamo", direccion+"/FamiliasEnAccion/AfectadosReclamo.jsp"))
            aux4 = insFld(aux3, gFld("Respuesta Reclamo", direccion+"/Salud/SaludReclamoRespuesta.jsp"))
            
        aux3 = insFld(aux2, gFld("Quejas", "javascript:undefined"))
            aux4 = insFld(aux3, gFld("Registro de Quejas", direccion+"/Salud/SaludQueja.jsp"))
            aux4 = insFld(aux3, gFld("Documentos", direccion+"/FamiliasEnAccion/DocumentoQuejas.jsp"))
            aux4 = insFld(aux3, gFld("Afectados por Queja", direccion+"/FamiliasEnAccion/AfectadosQuejas.jsp"))            
            aux4 = insFld(aux3, gFld("Respuesta a Quejas", direccion+"/Salud/SaludQuejaRespuesta.jsp"))
            
        aux3 = insFld(aux2, gFld("Configuraci&oacute;n B&aacute;sica", "javascript:undefined"))
            aux4 = insFld(aux3, gFld("Tipo Actividad", direccion+"/TablasBasicas/TipoActividad.jsp"))
            aux4 = insFld(aux3, gFld("Clasificaci&oacute;n Reclamo", direccion+"/TablasBasicas/ReclamoClasificacion.jsp"))
            aux4 = insFld(aux3, gFld("Tipo Reclamo", direccion+"/TablasBasicas/ReclamoTipo.jsp"))
            aux4 = insFld(aux3, gFld("Clasifica Respuesta", direccion+"/TablasBasicas/RespuestaClasificacion.jsp"))
            aux4 = insFld(aux3, gFld("Tipo Satisfacci&oacute;n", direccion+"/TablasBasicas/SatisfaccionTipo.jsp"))
            aux4 = insFld(aux3, gFld("Clasificaci&oacute;n Queja", direccion+"/TablasBasicas/QuejaClasificacion.jsp"))
            aux4 = insFld(aux3, gFld("Tipo Queja", direccion+"/TablasBasicas/TipoQueja.jsp"))

      aux2 = insFld(aux1, gFld("PRESTACI&Oacute;N SERVICIOS SALUD", "javascript:undefined"))
        aux3 = insFld(aux2, gFld("Autorizaciones Secretar&iacute;a de Salud", direccion+"/Salud/AutorizacionSecretaria.jsp"))
        aux3 = insFld(aux2, gFld("Usuarios Atendidos en IPS", direccion+"/Salud/UsuariosAtendidosIPS.jsp"))
        aux3 = insFld(aux2, gFld("Recepci&oacute;n Archivos RIPS", direccion+"/Salud/RecepcionArchivoRIPS.jsp"))
        aux3 = insFld(aux2, gFld("RIPS Peri&oacute;dicos", "javascript:undefined"))
            aux4 = insFld(aux3, gFld("RIPS EAPB", "javascript:undefined"))
                aux5 = insFld(aux4, gFld("Archivo de Control", direccion+"/Salud/ArchivoControlEAPB.jsp"))
                aux5 = insFld(aux4, gFld("Archivo Descripci&oacute;n", "javascript:undefined"))
                aux5 = insFld(aux4, gFld("Archivo Valores Totales", "javascript:undefined"))
                aux5 = insFld(aux4, gFld("RIPS Peri&oacute;dicos", "javascript:undefined"))
            aux4 = insFld(aux3, gFld("RIPS IPS", "javascript:undefined"))
                aux5 = insFld(aux4, gFld("Archivo de Control", direccion+"/Salud/ArchivoControlIPS.jsp"))
                aux5 = insFld(aux4, gFld("Archivo Descripci&oacute;n", direccion+"/Salud/ArchivoDescripcionIPS.jsp"))
                aux5 = insFld(aux4, gFld("RIPS Peri&oacute;dicos", "javascript:undefined"))
        aux3 = insFld(aux2, gFld("Detalle Archivos RIPS", "javascript:undefined"))
            aux4 = insFld(aux3, gFld("Estructura de Archivos", direccion+"/Salud/"))
            aux4 = insFld(aux3, gFld("Detalle Inconsistencia RIPS", direccion+"/Salud/DetalleInconsistenciaRIPS.jsp"))
            aux4 = insFld(aux3, gFld("Novedades RIPS por Dato", direccion+"/Salud/NovedadRIPSDato.jsp"))
        aux3 = insFld(aux2, gFld("Generaci&oacute;n Archivos", "javascript:undefined"))
            aux4 = insFld(aux3, gFld("RIPS EAPB", "javascript:undefined"))
            aux4 = insFld(aux3, gFld("RIPS IPS", "javascript:undefined"))
        aux3 = insFld(aux2, gFld("BI - Gesti&oacute;n Informaci&oacute;n", "javascript:undefined"))
            aux4 = insFld(aux3, gFld("Producci&oacute;n", "javascript:undefined"))
            aux4 = insFld(aux3, gFld("Morbilidad", "javascript:undefined"))
            aux4 = insFld(aux3, gFld("Facturaci&oacute;n", "javascript:undefined"))
            aux4 = insFld(aux3, gFld("Inteligencia de Negocios", "javascript:undefined"))
        aux3 = insFld(aux2, gFld("Configuraci&oacute;n B&aacute;sica", "javascript:undefined"))
            aux4 = insFld(aux3, gFld("B&aacute;sica", "javascript:undefined"))
                aux5 = insFld(aux4, gFld("&Aacute;rea General Entidad", direccion+"/TablasBasicas/AreaGeneralEntidad.jsp"))
                aux5 = insFld(aux4, gFld("Cobertura en Salud para Pago", direccion+"/TablasBasicas/CoberturaSaludPago.jsp"))
                aux5 = insFld(aux4, gFld("Especialidades o Profesiones", direccion+"/TablasBasicas/Especialidad.jsp"))
                aux5 = insFld(aux4, gFld("Grupo Sangu&iacute;neo", direccion+"/TablasBasicas/GrupoSanguineo.jsp"))
                aux5 = insFld(aux4, gFld("Niveles de Complejidad", direccion+"/TablasBasicas/NivelComplejidad.jsp"))
                aux5 = insFld(aux4, gFld("Tipo Personal de Salud", direccion+"/TablasBasicas/TipoPersonal.jsp"))
                aux5 = insFld(aux4, gFld("Tipo Pago Compartido", direccion+"/TablasBasicas/TipoPagoCompartido.jsp"))
                aux5 = insFld(aux4, gFld("Tipo Vinculaci&oacute;n Personal de Salud", direccion+"/TablasBasicas/TipoVinculacPersonal.jsp"))
                aux5 = insFld(aux4, gFld("Tipo de Turnos", direccion+"/TablasBasicas/TipoTurno.jsp"))
                aux5 = insFld(aux4, gFld("Valor M&aacute;ximo por Evento", direccion+"/TablasBasicas/ValorMaxEvento.jsp"))
            aux4 = insFld(aux3, gFld("Camas o Salas", "javascript:undefined"))
                aux5 = insFld(aux4, gFld("Camas", direccion+"/TablasBasicas/Cama.jsp"))
                aux5 = insFld(aux4, gFld("Tipo Habitaci&oacute;n Cama", direccion+"/TablasBasicas/TipoHabitacion.jsp"))
                aux5 = insFld(aux4, gFld("Tipo de Cama", direccion+"/TablasBasicas/TipoCama.jsp"))
                aux5 = insFld(aux4, gFld("Estado Cama", direccion+"/TablasBasicas/EstadoCama.jsp"))
                aux5 = insFld(aux4, gFld("Estado Sala", direccion+"/TablasBasicas/EstadoSala.jsp"))
                aux5 = insFld(aux4, gFld("Grupo Cama o Sala", direccion+"/TablasBasicas/GrupoCamaSala.jsp"))
                aux5 = insFld(aux4, gFld("Sala de Cirug&iacute;a", direccion+"/TablasBasicas/SalaCirugia.jsp"))
                aux5 = insFld(aux4, gFld("Subgrupo Cama o Sala", direccion+"/TablasBasicas/SubgrupoCamaSala.jsp"))
            aux4 = insFld(aux3, gFld("Accidentes o Riesgos", "javascript:undefined"))
                aux5 = insFld(aux4, gFld("Clase Riesgo Catastr&oacute;fico", direccion+"/TablasBasicas/ClaseRiesgoCatastrofe.jsp"))
                aux5 = insFld(aux4, gFld("Condici&oacute;n Accidentado", direccion+"/TablasBasicas/CondicionAccidentado.jsp"))
                aux5 = insFld(aux4, gFld("Definici&oacute;n Catastr&oacute;fica", direccion+"/TablasBasicas/DefinicionCatastrofica.jsp"))
                aux5 = insFld(aux4, gFld("Marca de Veh&iacute;culo", direccion+"/TablasBasicas/MarcaVehiculo.jsp"))
                aux5 = insFld(aux4, gFld("Tipo de Veh&iacute;culo", direccion+"/TablasBasicas/TipoVehiculo.jsp"))
                aux5 = insFld(aux4, gFld("Tipo Riesgo Catastr&oacute;fico", direccion+"/TablasBasicas/TipoRiesgoCatastrofe.jsp"))               
            aux4 = insFld(aux3, gFld("Ingreso o Salida", "javascript:undefined"))
                aux5 = insFld(aux4, gFld("Causas Externas", direccion+"/TablasBasicas/CausaExterna.jsp"))
                aux5 = insFld(aux4, gFld("Clase Triage", direccion+"/TablasBasicas/ClaseTriage.jsp"))
                aux5 = insFld(aux4, gFld("Destino Usuario o Conducta", direccion+"/TablasBasicas/DestinoSalida.jsp"))
                aux5 = insFld(aux4, gFld("Estado Ingreso", direccion+"/TablasBasicas/EstadoIngreso.jsp"))
                aux5 = insFld(aux4, gFld("Estado Salida", direccion+"/TablasBasicas/EstadoSalida.jsp"))
                aux5 = insFld(aux4, gFld("Finalidad Consulta", direccion+"/TablasBasicas/FinalidadConsulta.jsp"))
                aux5 = insFld(aux4, gFld("Finalidad Procedimiento", direccion+"/TablasBasicas/FinalidadProcedimiento.jsp"))
                aux5 = insFld(aux4, gFld("Clase Remisi&oacute;n", direccion+"/TablasBasicas/ClaseRemision.jsp"))
                aux5 = insFld(aux4, gFld("Tipo Solicitud de Servicios", direccion+"/TablasBasicas/TipoSolicServicio.jsp"))
                aux5 = insFld(aux4, gFld("Clasificaci&oacute;n Urgencias", direccion+"/TablasBasicas/ClaseUrgencia.jsp"))
                aux5 = insFld(aux4, gFld("V&iacute;as de Ingreso", direccion+"/TablasBasicas/ViaIngreso.jsp"))
            aux4 = insFld(aux3, gFld("Atenci&oacute;n", "javascript:undefined"))
                aux5 = insFld(aux4, gFld("Causas de Incapacidad", direccion+"/TablasBasicas/CausaIncapacidad.jsp"))
                aux5 = insFld(aux4, gFld("Grado Discapacidad", direccion+"/TablasBasicas/GradoDiscapacidad.jsp"))
                aux5 = insFld(aux4, gFld("Tipo Discapacidad", direccion+"/TablasBasicas/TipoDiscapacidad.jsp"))
                aux5 = insFld(aux4, gFld("Forma Realizaci&oacute;n Acto Quir&uacute;rgico", direccion+"/TablasBasicas/FormaRealActoQuirurg.jsp"))
                aux5 = insFld(aux4, gFld("Estado Historia Cl&iacute;nica", direccion+"/TablasBasicas/EstadoHistoriaClinica.jsp"))
                aux5 = insFld(aux4, gFld("Tipo de Tratamiento", direccion+"/TablasBasicas/TipoTratamiento.jsp"))
                aux5 = insFld(aux4, gFld("Tipo Intervenci&oacute;n Procedimiento Quiruoacute;rgico", direccion+"/TablasBasicas/TipoIntervencProced.jsp"))
                aux5 = insFld(aux4, gFld("Tipo de Anestesia", direccion+"/TablasBasicas/TipoAnestesia.jsp"))
                
      aux2 = insFld(aux1, gFld("SALUD P&Uacute;BLICA", "javascript:undefined"))
        aux3 = insFld(aux2, gFld("", "javascript:undefined"))
        aux3 = insFld(aux2, gFld("", "javascript:undefined"))
            aux4 = insFld(aux3, gFld("", "javascript:undefined"))

      /*aux2 = insFld(aux1, gFld("PROMOCI&Oacute;N DE SALUD", "javascript:undefined"))
        aux3 = insFld(aux2, gFld("", "javascript:undefined"))
        aux3 = insFld(aux2, gFld("", "javascript:undefined"))
            aux3 = insFld(aux3, gFld("", "javascript:undefined"))*/

      /*aux2 = insFld(aux1, gFld("RIESGOS PROFESIONALES", "javascript:undefined"))
        aux3 = insFld(aux2, gFld("", "javascript:undefined"))
        aux3 = insFld(aux2, gFld("", "javascript:undefined"))
        aux3 = insFld(aux2, gFld("", "javascript:undefined"))
        aux3 = insFld(aux2, gFld("", "javascript:undefined"))
        aux3 = insFld(aux2, gFld("", "javascript:undefined"))
            aux4 = insFld(aux3, gFld("", "javascript:undefined"))
            aux4 = insFld(aux3, gFld("", "javascript:undefined"))
            aux4 = insFld(aux3, gFld("", "javascript:undefined"))*/

      /*aux2 = insFld(aux1, gFld("EMERGENCIAS Y DESASTRES", "javascript:undefined"))
            aux3 = insFld(aux2, gFld("", "javascript:undefined"))
            aux3 = insFld(aux2, gFld("", "javascript:undefined"))*/

      aux2 = insFld(aux1, gFld("BI (GESTI&Oacute;N INFORMACI&Oacute;N)", "javascript:undefined"))
        aux3 = insFld(aux2, gFld("", "javascript:undefined"))
            aux4 = insFld(aux3, gFld("", "javascript:undefined"))
            
      aux2 = insFld(aux1, gFld("SEGURIDAD", "javascript:undefined"))
            aux3 = insFld(aux2, gFld("", "javascript:undefined"))
            aux3 = insFld(aux2, gFld("", "javascript:undefined"))

        aux2 = insFld(aux1, gFld("PERFILES DE USUARIO", "javascript:undefined"))
            aux3 = insFld(aux2, gFld("", "javascript:undefined"))
            aux3 = insFld(aux2, gFld("", "javascript:undefined"))

       aux2 = insFld(aux1, gFld("CONFIGURACI&Oacute;N GENERAL", "javascript:undefined"))
            aux3 = insFld(aux2, gFld("&Aacute;rea Geogr&aacute;fica", "javascript:undefined"))
                aux4 = insFld(aux3, gFld("Agrupaci&oacute;n Municipio", direccion+"/TablasBasicas/AgrupacionGeoMunicipio.jsp"))
                aux4 = insFld(aux3, gFld("Barrios", direccion+"/TablasBasicas/Barrio.jsp"))
                aux4 = insFld(aux3, gFld("Departamentos", direccion+"/TablasBasicas/Departamento.jsp"))
                aux4 = insFld(aux3, gFld("Municipios", direccion+"/TablasBasicas/Municipio.jsp"))
                aux4 = insFld(aux3, gFld("Regiones Departamento", direccion+"/TablasBasicas/RegionGeoDepto.jsp"))
                aux4 = insFld(aux3, gFld("Sectores", direccion+"/TablasBasicas/SectorGeografico.jsp"))
                aux4 = insFld(aux3, gFld("Subgrupo Municipio", direccion+"/TablasBasicas/SubgrupoGeografico.jsp"))
                aux4 = insFld(aux3, gFld("Tipo de Agrupaci&oacute;n", direccion+"/TablasBasicas/AgrupacionGeografica.jsp"))
                aux4 = insFld(aux3, gFld("Tipo Regi&oacute;n Geogr&aacute;fica", direccion+"/TablasBasicas/RegionGeografica.jsp"))
                aux4 = insFld(aux3, gFld("Tipo Subgrupo Municipio", direccion+"/TablasBasicas/TipoSubgrupoGeo.jsp"))
                aux4 = insFld(aux3, gFld("Zonas", direccion+"/TablasBasicas/ZonaGeografica.jsp"))
            aux3 = insFld(aux2, gFld("Actividad de Salud", "javascript:undefined"))
                aux4 = insFld(aux3, gFld("Parametrizaci&oacute;n", "javascript:undefined"))
                    aux5 = insFld(aux4, gFld("Actividades en Salud", direccion+"/TablasBasicas/ActividadSalud.jsp"))
                    aux5 = insFld(aux4, gFld("Actividad Agrupada IPS", direccion+"/TablasBasicas/ActividadIps.jsp"))
                    aux5 = insFld(aux4, gFld("Actividad por Edades", direccion+"/TablasBasicas/ActividadEdad.jsp"))
                    aux5 = insFld(aux4, gFld("Actividad por Paquetes", direccion+"/TablasBasicas/ActividadPaquete.jsp"))
                    aux5 = insFld(aux4, gFld("Actividad por Plan de Salud", direccion+"/TablasBasicas/ActividadPlanSalud.jsp"))
                    aux5 = insFld(aux4, gFld("Actividad por Programa", direccion+"/TablasBasicas/ActividadPrograma.jsp"))
                    aux5 = insFld(aux4, gFld("Actividad por Tipo Personal", direccion+"/TablasBasicas/ActividadTipoPersonal.jsp"))
                    aux5 = insFld(aux4, gFld("Homologaci&oacute;n de Actividades", direccion+"/TablasBasicas/HomologacionActividad.jsp"))
                    aux5 = insFld(aux4, gFld("Manual de Actividades", direccion+"/TablasBasicas/ManualActividad.jsp"))
                    aux5 = insFld(aux4, gFld("Manual de Liquidaci&oacute;n Actividades", direccion+"/TablasBasicas/ManualLiquidacion.jsp"))
                    aux5 = insFld(aux4, gFld("Plan Tarifas de Actividades", direccion+"/TablasBasicas/PlanTarifa.jsp"))
                    aux5 = insFld(aux4, gFld("Programa Cumplimiento por Actividad", direccion+"/TablasBasicas/CumplimActPrograma.jsp"))
                    aux5 = insFld(aux4, gFld("Programa Matriz Metas de Actividad", direccion+"/TablasBasicas/ProgramaMetaActividad.jsp"))
                    aux5 = insFld(aux4, gFld("Programa PEyDT Ciclos", direccion+"/TablasBasicas/ProgramaCiclo.jsp"))
                    aux5 = insFld(aux4, gFld("Protocolo Actividad", direccion+"/TablasBasicas/ProtocoloActividad.jsp"))
                    aux5 = insFld(aux4, gFld("Tareas por Actividad", direccion+"/TablasBasicas/TareasActividad.jsp"))                    
                aux4 = insFld(aux3, gFld("B&aacute;sicas", "javascript:undefined"))
                    aux5 = insFld(aux4, gFld("&Aacute;mbito Actividad", direccion+"/TablasBasicas/AmbitoActividad.jsp"))
                    aux5 = insFld(aux4, gFld("Categor&iacute;a Actividad", direccion+"/TablasBasicas/CategoriaActividad.jsp"))
                    aux5 = insFld(aux4, gFld("Clase Actividad", direccion+"/TablasBasicas/ClaseActividad.jsp"))
                    aux5 = insFld(aux4, gFld("Estado Cumplimiento Actividad", direccion+"/TablasBasicas/EstadoCumplimActividad.jsp"))
                    aux5 = insFld(aux4, gFld("Grupo Actividad", direccion+"/TablasBasicas/GrupoActividad.jsp"))
                    aux5 = insFld(aux4, gFld("Grupos Quir&uacute;rgicos", direccion+"/TablasBasicas/GrupoQuirurgico.jsp"))
                    aux5 = insFld(aux4, gFld("Grupos Quir&uacute;rgicos Actividad", direccion+"/TablasBasicas/GrupoQuirurgicoActividad.jsp"))
                    aux5 = insFld(aux4, gFld("Grupos Quir&uacute;rgicos Factores", direccion+"/TablasBasicas/FactorGrupoQuirurgico.jsp"))
                    aux5 = insFld(aux4, gFld("Subgrupo Actividades", direccion+"/TablasBasicas/SubgrupoActividad.jsp"))
                    aux5 = insFld(aux4, gFld("Tipo Actividad", direccion+"/TablasBasicas/TipoActividad.jsp"))
                    aux5 = insFld(aux4, gFld("Tipo de Esquema Actividad", direccion+"/TablasBasicas/EsquemaActividad.jsp"))
                aux4 = insFld(aux3, gFld("Tablas Generales", "javascript:undefined"))
                    aux5 = insFld(aux4, gFld("Conceptos de Servicios", direccion+"/TablasBasicas/ConceptoServicio.jsp"))
                    aux5 = insFld(aux4, gFld("Plan Salud o de Beneficios", direccion+"/TablasBasicas/PlanSalud.jsp"))
                    aux5 = insFld(aux4, gFld("Programas PEyDT Normas", direccion+"/TablasBasicas/ProgramaPromPrev.jsp"))
                    aux5 = insFld(aux4, gFld("Tipo de Metodolog&iacute;a de Tarifas", direccion+"/TablasBasicas/TipoMetodologia.jsp"))
                    aux5 = insFld(aux4, gFld("Tipo de Riesgo", direccion+"/TablasBasicas/TipoRiesgoCatastrofe.jsp"))
                    aux5 = insFld(aux4, gFld("Tipo Plan de Tarifas", direccion+"/TablasBasicas/TipoPlanTarifa.jsp"))
                    aux5 = insFld(aux4, gFld("UVR Rangos", direccion+"/TablasBasicas/Uvr.jsp"))
            aux3 = insFld(aux2, gFld("Suministros", "javascript:undefined"))
                aux4 = insFld(aux3, gFld("Parametrizaci&oacute;n Suministros", "javascript:undefined"))
                    aux5 = insFld(aux4, gFld("Homologaci&oacute;n de Suministros", direccion+"/TablasBasicas/HomologSuministro.jsp"))
                    aux5 = insFld(aux4, gFld("Manual Liquidaci&oacute;n de Suministros", direccion+"/TablasBasicas/ManualLiquSuminitro.jsp"))
                    aux5 = insFld(aux4, gFld("Planes de Tarifas de los Suministros", direccion+"/TablasBasicas/PlanTarifaSuminis.jsp"))
                    aux5 = insFld(aux4, gFld("Programas Cumplimiento por Suministro", direccion+"/TablasBasicas/ProgramCumplSumin.jsp"))
                    aux5 = insFld(aux4, gFld("Programas Matriz de Metas de Suministros", direccion+"/TablasBasicas/PrograMetaSuministro.jsp"))
                    aux5 = insFld(aux4, gFld("Suministro por Programa", direccion+"/TablasBasicas/SuministroPrograma.jsp"))
                    aux5 = insFld(aux4, gFld("Suministros", direccion+"/TablasBasicas/Suministros.jsp"))
                    aux5 = insFld(aux4, gFld("Suministros Comerciales", direccion+"/TablasBasicas/SuministroComerc.jsp"))
                    aux5 = insFld(aux4, gFld("Suministros por Edades", direccion+"/TablasBasicas/SuministroEdad.jsp"))
                    aux5 = insFld(aux4, gFld("Suministros por Tipo de Personal en Salud", direccion+"/TablasBasicas/SuministroTipoPersonal.jsp"))
                    aux5 = insFld(aux4, gFld("Tareas por Suministro", direccion+"/TablasBasicas/TareaSuministro.jsp"))
                aux4 = insFld(aux3, gFld("B&aacute;sicas", "javascript:undefined"))
                    aux5 = insFld(aux4, gFld("Clase de Suministro", direccion+"/TablasBasicas/ClaseSuministro.jsp"))
                    aux5 = insFld(aux4, gFld("Concentraciones", direccion+"/TablasBasicas/Concentracion.jsp"))
                    aux5 = insFld(aux4, gFld("Estado Proveedor", direccion+"/TablasBasicas/EstadoProveedor.jsp"))
                    aux5 = insFld(aux4, gFld("Forma Farmac&eacute;utica", direccion+"/TablasBasicas/FormaFarmacia.jsp"))
                    aux5 = insFld(aux4, gFld("Grupo Suministros", direccion+"/TablasBasicas/GrupoSuministro.jsp"))
                    aux5 = insFld(aux4, gFld("Proveedores o Laboratorios", direccion+"/TablasBasicas/Proveedor.jsp"))
                    aux5 = insFld(aux4, gFld("Subgrupos de Suministros", direccion+"/TablasBasicas/SubgrupoSuministro.jsp"))
                    aux5 = insFld(aux4, gFld("Tipo de Medicamento", direccion+"/TablasBasicas/TipoMedicamento.jsp"))
                    aux5 = insFld(aux4, gFld("Tipo Proveedor", direccion+"/TablasBasicas/TipoProveedor.jsp"))
                    aux5 = insFld(aux4, gFld("Unidades de Medida", direccion+"/TablasBasicas/UnidadMedida.jsp"))
                    aux5 = insFld(aux4, gFld("V&iacute;as de Administraci&oacute;n", direccion+"/TablasBasicas/ViasAdmin.jsp"))
              aux3 = insFld(aux2, gFld("Diagn&oacute;sticos", "javascript:undefined"))
                aux4 = insFld(aux3, gFld("Parametrizaci&oacute;n Dagn&oacute;sticos", "javascript:undefined"))
                    aux5 = insFld(aux4, gFld("Diagn&oacute;stico", direccion+"/TablasBasicas/Diagnostico.jsp"))
                    aux5 = insFld(aux4, gFld("Diagn&oacute;stico 298 Causas", direccion+"/TablasBasicas/Diagnostico298.jsp"))
                    aux5 = insFld(aux4, gFld("Diagn&oacute;stico a 3 Caracteres", direccion+"/TablasBasicas/Diagnostico3Char.jsp"))
                    aux5 = insFld(aux4, gFld("Manual Liquidaci&oacute;n de Diagn&oacute;stico", direccion+"/TablasBasicas/ManualLiquDiagn.jsp"))
                    aux5 = insFld(aux4, gFld("Plan Tarifas de Diagn&oacute;stico", direccion+"/TablasBasicas/PlanTarifaDiagn.jsp"))
                    aux5 = insFld(aux4, gFld("Protocolos de Diagn&oacute;stico", direccion+"/TablasBasicas/ProtocoloDiagnostico.jsp"))
                aux4 = insFld(aux3, gFld("Relaci&oacute;n en Diagn&oacute;sticos", "javascript:undefined"))
                    aux5 = insFld(aux4, gFld("Diagn&oacute;sticos Agrupados por IPS", direccion+"/TablasBasicas/DiagnosticoIps.jsp"))
                    aux5 = insFld(aux4, gFld("Diagn&oacute;stico con Actividades Relacionadas", direccion+"/TablasBasicas/DiagnActividadRel.jsp"))
                    aux5 = insFld(aux4, gFld("Diagn&oacute;stico por Ciclo de Programas", direccion+"/TablasBasicas/DiagnCicloPrograma.jsp"))
                    aux5 = insFld(aux4, gFld("Diagn&oacute;stico por Edades", direccion+"/TablasBasicas/DiagnosticoEdad.jsp"))
                    aux5 = insFld(aux4, gFld("Diagn&oacute;stico por Plan de Salud", direccion+"/TablasBasicas/DiagnPlanSalud.jsp"))
                    aux5 = insFld(aux4, gFld("Diagn&oacute;stico por Programa", direccion+"/TablasBasicas/DiagnosticoPrograma.jsp"))
                    aux5 = insFld(aux4, gFld("Diagn&oacute;stico por Tipo de Personal", direccion+"/TablasBasicas/DiagnTipoPersonal.jsp"))
                    aux5 = insFld(aux4, gFld("Homologaci&oacute;n de Diagn&oacute;sticos", direccion+"/TablasBasicas/HomologacionDiagn.jsp"))
                    aux5 = insFld(aux4, gFld("Tareas por Diagn&oacute;stico", direccion+"/TablasBasicas/TareaDiagnostico.jsp"))
                aux4 = insFld(aux3, gFld("Tablas Generales", "javascript:undefined"))
                    aux5 = insFld(aux4, gFld("&Aacute;mbito Diagn&oacute;stico", direccion+"/TablasBasicas/AmbitoDiagnostico.jsp"))
                    aux5 = insFld(aux4, gFld("Clase Diagn&oacute;stico", direccion+"/TablasBasicas/ClaseDiagnostico.jsp"))
                    aux5 = insFld(aux4, gFld("Clasificaci&oacute;n o Manual de Diagn&oacute;stico", direccion+"/TablasBasicas/ManualDiagnostico.jsp"))
                    aux5 = insFld(aux4, gFld("Evento Epidemiol&oacute;gico", direccion+"/TablasBasicas/EventoEpidemiologico.jsp"))
                    aux5 = insFld(aux4, gFld("Grupo Diagn&oacute;stico", direccion+"/TablasBasicas/GrupoDiagnostico.jsp"))
                    aux5 = insFld(aux4, gFld("Subgrupo Diagn&oacute;stico", direccion+"/TablasBasicas/SubgrupoDiagnostico.jsp"))
                    aux5 = insFld(aux4, gFld("Tipo Diagn&oacute;stico", direccion+"/TablasBasicas/TipoDiagnostico.jsp"))
                    aux5 = insFld(aux4, gFld("Tipo Diagn&oacute;stico Relacionado", direccion+"/TablasBasicas/TipoDiagRelacionado.jsp"))
            aux3 = insFld(aux2, gFld("Entidad Salud", direccion+"/TablasBasicas/EntidadSalud.jsp"))
            aux3 = insFld(aux2, gFld("Normatividad", direccion+"/TablasBasicas/Normas.jsp"))
            aux3 = insFld(aux2, gFld("UPC", direccion+"/TablasBasicas/Upcs.jsp"))
            aux3 = insFld(aux2, gFld("Parametrizaci&oacute;n Sistema", "javascript:undefined"))
                aux4 = insFld(aux3, gFld("Informaci&oacute;n Empresa", direccion+"/TablasBasicas/InformacionEmpresa.jsp"))
                aux4 = insFld(aux3, gFld("Control de Consecutivos", direccion+"/TablasBasicas/ControlConsecutivo.jsp"))
            aux3 = insFld(aux2, gFld("Configuraci&oacute;n B&aacute;sica", "javascript:undefined"))
                aux4 = insFld(aux3, gFld("Cuentas y Bancos", "javascript:undefined"))
                    aux5 = insFld(aux4, gFld("Bancos", direccion+"/TablasBasicas/Banco.jsp"))
                    aux5 = insFld(aux4, gFld("Cuentas Bancarias", direccion+"/TablasBasicas/CuentaBancaria.jsp"))
                    aux5 = insFld(aux4, gFld("Plan de Cuentas", direccion+"/TablasBasicas/CuentaContable.jsp"))
                    aux5 = insFld(aux4, gFld("Plan de Cuentas Disponiblidad", direccion+"/TablasBasicas/DisponibCuentaContable.jsp"))
                    aux5 = insFld(aux4, gFld("Plan de Cuentas Estados", direccion+"/TablasBasicas/EstadoCuentaContable.jsp"))
                    aux5 = insFld(aux4, gFld("Plan de Cuentas Grupos", direccion+"/TablasBasicas/GrupoCuentaContable.jsp"))
                    aux5 = insFld(aux4, gFld("Plan de Cuentas Naturaleza", direccion+"/TablasBasicas/NaturalezaCuentaContable.jsp"))
                    aux5 = insFld(aux4, gFld("Plan de Cuentas Tipo", direccion+"/TablasBasicas/TipoCuentaContable.jsp"))
                    aux5 = insFld(aux4, gFld("Plan de Cuentas Tipo de Grupo", direccion+"/TablasBasicas/TipoGrupoContable.jsp"))
                    aux5 = insFld(aux4, gFld("Sucursales Bancarias", direccion+"/TablasBasicas/SucursalBanco.jsp"))
                    aux5 = insFld(aux4, gFld("Tipo de Cuenta Bancaria", direccion+"/TablasBasicas/TipoCuentaBanco.jsp"))
                    aux5 = insFld(aux4, gFld("Tipo Entidad Financiera", direccion+"/TablasBasicas/TipoEntFinanciera.jsp"))                    
                aux4 = insFld(aux3, gFld("Procesos Campos", "javascript:undefined"))
                    aux5 = insFld(aux4, gFld("Campos Valores Permitidos", direccion+"/TablasBasicas/ValorPermitidoCampo.jsp"))
                    aux5 = insFld(aux4, gFld("Lista de Campos", direccion+"/TablasBasicas/ListaCamposArchivo.jsp"))
                    aux5 = insFld(aux4, gFld("Lista de Procesos", direccion+"/TablasBasicas/ListaProceso.jsp"))
                    aux5 = insFld(aux4, gFld("Tareas", direccion+"/TablasBasicas/Tareas.jsp"))
                aux4 = insFld(aux3, gFld("Tablas Generales", "javascript:undefined"))
                    aux5 = insFld(aux4, gFld("Actividad Econ&oacute;mica", direccion+"/TablasBasicas/ActividadEconomica.jsp"))
                    aux5 = insFld(aux4, gFld("Estado Autorizaci&oacute;n", direccion+"/TablasBasicas/EstadoAutorizacion.jsp"))
                    aux5 = insFld(aux4, gFld("Cargos", direccion+"/TablasBasicas/Cargo.jsp"))
                    aux5 = insFld(aux4, gFld("Concepto Detalle Valores", direccion+"/TablasBasicas/DetalleConcValor.jsp"))
                    aux5 = insFld(aux4, gFld("Dias No H&aacute;biles del A&nacute;o", direccion+"/TablasBasicas/DiasNoHabiles.jsp"))
                    aux5 = insFld(aux4, gFld("Empresas", direccion+"/TablasBasicas/Empresa.jsp"))
                    aux5 = insFld(aux4, gFld("Estado Registro RIPS", direccion+"/TablasBasicas/EstadoRegRips.jsp"))
                    aux5 = insFld(aux4, gFld("Formato Archivos", direccion+"/TablasBasicas/FormatoArchivo.jsp"))
                    aux5 = insFld(aux4, gFld("Glosario de T&eacute;rminos", direccion+"/TablasBasicas/GlosarioTerminos.jsp"))
                    aux5 = insFld(aux4, gFld("IPC", direccion+"/TablasBasicas/Ipc.jsp"))
                    aux5 = insFld(aux4, gFld("M&eacute;todo Ajuste de Valores", direccion+"/TablasBasicas/MetodoAjuste.jsp"))
                    aux5 = insFld(aux4, gFld("Ocupaciones", direccion+"/TablasBasicas/Ocupacion.jsp"))
                    aux5 = insFld(aux4, gFld("Clase Persona", direccion+"/TablasBasicas/ClasePersona.jsp"))
                    aux5 = insFld(aux4, gFld("Tipo Concepto Valor", direccion+"/TablasBasicas/TipoConceptoValor.jsp"))
                    aux5 = insFld(aux4, gFld("Tipo Ajuste de Valores", direccion+"/TablasBasicas/TipoAjusteValor.jsp"))
                    aux5 = insFld(aux4, gFld("Tipo Contribuyente", direccion+"/TablasBasicas/TipoContribuyente.jsp"))
                    aux5 = insFld(aux4, gFld("Tipo Per&iacute;odo de Tiempo", direccion+"/TablasBasicas/TipoPeriodo.jsp"))
              aux3 = insFld(aux2, gFld("Diseño Base de Datos", "javascript:undefined"))